# Generated by Django 5.0.3 on 2024-04-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_bq', models.IntegerField()),
                ('data_coleta', models.DateField()),
                ('data_entrada', models.DateField()),
                ('cliente', models.CharField(max_length=45)),
                ('codigo_amostra', models.IntegerField()),
                ('amostra', models.CharField(max_length=45)),
                ('peso', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('classificacao', models.CharField(max_length=10)),
                ('obs', models.TextField()),
            ],
        ),
    ]
