# Generated by Django 5.0.3 on 2024-04-30 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_dadosformulario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosformulario',
            name='id',
            field=models.AutoField(default=datetime.datetime(2024, 4, 30, 14, 48, 32, 544374, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosformulario',
            name='codigo_bq',
            field=models.IntegerField(),
        ),
    ]
