# Generated by Django 5.0.3 on 2024-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_dadosformulario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosformulario',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
