# Generated by Django 5.0.3 on 2024-04-30 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_dadosformulario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosformulario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosformulario',
            name='codigo_bq',
            field=models.IntegerField(),
        ),
    ]
